### ISSUE TITLE
app.sidekik.xyz is offline And i am not able to find its source code.

### ISSUE THREAD

**Issue by unamewiki** [mistersingh179/sidekik-demo-1#1]
Hello,

I wanted to test out https://app.sidekik.xyz/, but it seems it is no longer online. I downloaded the site from https://archive.org/web/ and set it up locally using Python3's HTTP server (python3 -m http.server 8457), but the Sync Directory and Upload Files features are not working. Is the source code of the site available publicly?

```
$ tree
.
├── favicon.ico
├── index.html
├── logo192.png
├── manifest.json
├── sitemap.xml
└── static
    ├── css
    │   └── main.51a60fb2.css
    └── js
        └── main.f45920f0.js

4 directories, 7 files
```
![Screenshot_2024-01-16_11-35-00](https://github.com/mistersingh179/sidekik-demo-1/assets/114335196/e5b52222-aa63-47e3-ad70-862d94cca11a)

**Comment by mistersingh179** [comment]
this maybe because you are NOT running on an https domain, and the browser is not trusting the domain and thus not allowing  local drive access.
You can try it on https://sidekik.pages.dev instead.

**Comment by unamewiki** [comment]
> this maybe because you are NOT running on an https domain, and the browser is not trusting the domain and thus not allowing local drive access. You can try it on https://sidekik.pages.dev instead.

Thanks For sharing the link to online website.
